name = "sharex"
account_id = "7ceaca74043b46ad1106191ebc2bbbdd"
workers_dev = true
routes = [
	{pattern = "share.claireskye.com", zone_name = "claireskye.com"}
	]

compatibility_date = "2022-10-31"
compatibility_flags = ["nodejs_compat"]
main = "./src/index.ts"

[[r2_buckets]]
bucket_name = "sharex-files"
preview_bucket_name = "sharex-files"
binding = "R2_BUCKET"

[vars]
# Change to the domain your Public Bucket is connected to.
#CUSTOM_PUBLIC_BUCKET_DOMAIN = "custom-bucket.domain.tld"
# Change to not let the worker serve files, only allowing traffic through the Public Bucket. Do not set if you have old links pointing to the worker.
#ONLY_ALLOW_ACCESS_TO_PUBLIC_BUCKET = true